# Generated by Django 4.1.3 on 2023-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_price_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(max_length=16),
        ),
    ]
